### ISSUE TITLE
halo custom edition will not repackage maps / halo 2 vista repackaged maps not compatible

### ISSUE THREAD

**Issue by Crugnok** [num0005/Osoyoos-Launcher#24]
hi,

i tried to repackage maps for custom edition but it doesn't work as the command prompt says;

usage: tool.exe verb <required options..> [non-required options]
  build-cache-file <scenario-name> <classic|remastered> [resource-map-usage<none|read|read_write>] [log-tag-loads]
Press any key to continue . . .

tried including classic and it just ends up repackaging a map for the mcc build.

for halo 2 vista it just repackages maps for halo 2 mcc update instead of halo 2 vista and the game won't launch because of that 
as the maps aren't compatible.

are we not able to rebuild maps for halo custom edition and halo 2 vista yet with your tool?

**Comment by num0005** [comment]
Is the profile configured correctly? It kinda sounds like a misconfiguration.

**Comment by Crugnok** [comment]
tried it several times, just keeps packaging the maps for halo 2 mcc update.

mcc is not ticked in the profile settings, but for some reason it doesn't make h2v maps, only mcc h2 maps.

**Comment by General-101** [comment]
Show your profile settings for your CE and H2V profile. I'm not seeing this issue on latest on my end.
What launcher version are you on? Should be in the about page. Just redownload latest if you're not sure.

**Comment by Crugnok** [comment]
![H2VEK](https://user-images.githubusercontent.com/88882159/152975722-2e257f3b-17e4-4bce-a656-3b0c2d181d8f.jpg)
that's my profile settings, see mcc isn't ticked but when i try and repack any of the campaign maps it only makes mcc halo 2 maps which i obviously can't use on halo 2 vista.

**Comment by num0005** [comment]
The launcher doesn't package the maps on it's own, it uses the toolkit for that. Changing the build type won't change what maps it builds it will just break it.

Looking at the paths there, those look like MCC tools. Set the build type to MCC and it will work for MCC.

As for H2V you need to get a copy of the H2VEK/Halo 2 Map Editor (I think the install disk referred to it as a map editor). Not sure right now what MCC tags will or won't work with H2V but off the top of my head I don't expect sound or rasterizer tags to work.

**Comment by num0005** [comment]
Once you get H2VEK setup you just need to create a new launcher profile and fill in the correct paths.

**Comment by num0005** [comment]
Same deal with custom edition, you need to install the HEK and/or Invader to package the maps but there is better compatibility there so you might be able to use the MCC tools for editing the level and only use H1CE tools for building the cache.

The launcher doesn't currently support Invader so if you decide to use that you will need figure out how to build a cache with it on your own.

**Comment by Crugnok** [comment]
i see but the problem is how do you repackage the campaign maps on the original toolkit? i have the original game installed but there is not a full tag package.

**Comment by num0005** [comment]
the HEK (H1CE editing kit) can afaik be downloaded by anyone. H2VEK was included on the install DVD.

**Comment by num0005** [comment]
> i see but the problem is how do you repackage the campaign maps on the original toolkit? i have the original game installed but there is not a full tag package, the editor only installed a limited set of tags. either way, i've almost done re-creating the mods using assembly but it would be nice to do it via the editor as well.

Not sure, there is a tag extractor and some tags use the same format.

**Comment by Crugnok** [comment]
i have a look for a tag extractor as that will be handy. i already have the hek installed. i already re done my mods for halo 1 and then converted the maps to custom editon to save time.

thanks for the info / tips.
