### ISSUE TITLE
Why can I only open certain osoyoos versions?

### ISSUE THREAD

**Issue by Cosmic884** [num0005/Osoyoos-Launcher#39]
When I try to open certain versions nothing happens after clicking yes on the windows protected your pc prompt

**Comment by num0005** [comment]
could you share a screenshot of the message you get?

**Comment by agentduckman12** [comment]
> could you share a screenshot of the message you get?

i have the same issue for me it wont even give a message

**Comment by num0005** [comment]
does this still happen?
