### ISSUE TITLE
Hide console windows

### ISSUE THREAD

**Issue by dt192** [num0005/Osoyoos-Launcher#53]
**Is your feature request related to a problem? Please describe.**
A great time for me to iterate on light bakes is while I'm working, however having all the console windows keep popping up over what I'm trying to do makes it a no go.

**Describe the solution you'd like**
Could you add the option to hide the windows and pipe the console output to either log files or an internal window of the app.

**Comment by num0005** [comment]
gonna take a shot at implementing this now

**Comment by num0005** [comment]
Implemented this in the latest pre-release version for lightmaps.
![image](https://github.com/num0005/Osoyoos-Launcher/assets/30047358/f282f231-ff1c-458c-ac5e-ab757cba3427)
