### ISSUE TITLE
Include instructions for how to use the launcher

### ISSUE THREAD

**Issue by ghost** [num0005/Osoyoos-Launcher#6]
Where do I get launcher program to launch?

**Comment by num0005** [comment]
Just download the launcher and run it, you might need to install the dotnet 5 runtime if you haven't already.

**Comment by Steeleclipse** [comment]
Instructions unclear. Penis stuck in blender. 

Please add more information than just 'download the launcher and run it'. What file is the launcher? Do I run it just by double clicking it or do I need to launch it a specific way?

**Comment by num0005** [comment]
going to lock this for now.
